#!/bin/bash

source "$HOME/.homesick/repos/dotfiles/cli/profile"

source "$HOME/.homesick/repos/dotfiles/cli/bash/colors"

system=$(uname -a)
if [[ $system =~ "Linux" ]]; then
    source "$HOME/.homesick/repos/dotfiles/cli/bash/rc.linux"
fi
if [[ $system =~ "Darwin" ]]; then
    source "$HOME/.homesick/repos/dotfiles/cli/bash/rc.osx"
fi
if [[ $system =~ "FreeBSD" ]]; then
    source "$HOME/.homesick/repos/dotfiles/cli/bash/rc.freebsd"
fi
if [[ $system == "MINGW32_NT-6.1" ]]; then
    source "$HOME/.homesick/repos/dotfiles/cli/bash/rc.mingw"
fi
unset system

source "$HOME/.homesick/repos/homeshick/completions/homeshick-completion.bash"
source "$HOME/.homesick/repos/dotfiles/cli/bash/completion"

source "$HOME/.homesick/repos/dotfiles/cli/aliases.sh"
source "$HOME/.homesick/repos/dotfiles/cli/functions.sh"

homeshick --quiet refresh 56 "homeshick dotfiles rc-files oh-my-zsh sublime-text-3-settings"

if [[ ! -n "$HOSTNAME" ]]; then
	HOSTNAME=$(hostname -s)
fi
