#!/bin/sh

if find '/etc/profile.d/' -name '*.sh' -type f -mindepth 1 -print -quit 2>/dev/null | grep -q .; then
  for file in /etc/profile.d/*.sh; do
    source "$file"
  done
  unset file
fi

# Add dotfiles/bin to PATH
PATH="$PATH:$HOME/.homesick/repos/dotfiles/bin"

# Enable true color for micro
MICRO_TRUECOLOR=1

# This is all we need to set, forget about LC_ALL, LC_CTYPE, LANG etc.
export LANGUAGE='en_US.UTF-8'

# Aaand then there is python, which doesn't seem to understand how these GNU variables work...
export LC_CTYPE='en_US.UTF-8'

export SVN_EDITOR="nano -t"
export GIT_EDITOR="nano -t"
export EDITOR='nano'
export PAGER='less'

# Enable colorized output in gnu tools (like ls on macOS)
export CLICOLOR=true

if [ -n "$SERVER_ENV" ]; then
  EMAIL='___@yourdomain.com'
  DEFAULT_USER='___'
fi

if [ -e "$HOME/.localenv" ]; then
  source "$HOME/.localenv"
fi

export LESS='-F -g -i -M -R -W -X -z-4'
