Vagrant.configure("2") do |config|
	config.ssh.forward_agent = true
	
	config.vm.provider "virtualbox" do |vbox| 
		vbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vbox.customize ["guestproperty", "set", :id,
		                "\"/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold\"",
		                "1000"]
	end
end
